# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: Bash@3
  displayName: 'Remove publish dir'
  inputs:
    targetType: 'inline'
    script: |
      rm -rf $(build.artifactstagingdirectory)/RemindersAPI
- task: DotNetCoreCLI@2
  displayName: 'Publish API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/RemindersAPI.csproj'
    arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/RemindersAPI --no-build
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish RemindersAPI Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/RemindersAPI'
    ArtifactName: 'RemindersAPI-artifact'
    publishLocation: Container